### ISSUE TITLE
[solved] expected all tensors to be on the same device

### ISSUE THREAD

**Issue by deefster** [Nick088Official/SuperPrompt-v1#1]
In the jupyter notebook I had to add 
`model.to(device)`
just before the call to model.generate

I also needed to add to resolve a missing dependency.
`!pip install sentencepiece`

**Comment by Nick088Official** [comment]
Hey sorry for the late response, thank you very much for making me notice this! I updated both colabs with your fix and credited you in the commit long description! I will close this now, if you get any other issues let me know
