### ISSUE TITLE
Unable to install GUI

### ISSUE THREAD

**Issue by barepixels** [Nick088Official/SuperPrompt-v1#2]
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
No module named 'dockerpycreds'
--------------

F:\AI-SOFTWARES>pip install dockerpycreds
ERROR: Could not find a version that satisfies the requirement dockerpycreds (from versions: none)
ERROR: No matching distribution found for dockerpycreds

**Comment by barepixels** [comment]
I modify "install_and_run_gradio_ui.bat" and got it installed and working

--------------------------------

[u/echo](https://www.reddit.com/user/echo/) off

python -m venv venv

call .\venv\Scripts\activate.bat

cd "Python Scripts"

python install_and_run_gradio_ui.py

pause

**Comment by Nick088Official** [comment]
Thank you, i updated the Repo so both no ui and ui have venvs, i will close this issue
