### ISSUE TITLE
Why does the prompt always suggest the same expanded prompt, even if the seed is set to 0?

### ISSUE THREAD

**Issue by andupotorac** [Nick088Official/SuperPrompt-v1#4]
These are my settings <img width="1524" alt="image" src="https://github.com/Nick088Official/SuperPrompt-v1/assets/3269738/059d376f-5c08-4f80-b3ff-00aef0a22306">

**Comment by Nick088Official** [comment]
Hello, could you please retry with setting the temperature to an higher value such as 0,7? Temperature is an important parameter that controls the creativity, for the rest i think you can leave the same settings, even if i suggest you to put higher max new tokens. Please tell me if it helped or not so i could look into it

**Comment by andupotorac** [comment]
Note this might have been an issue with the initial code, b/c I looked at this other implementation and it mentioned fixing this same problem: https://github.com/SLAPaper/sd-webui-pe?tab=readme-ov-file#update-20240320.

**Comment by Nick088Official** [comment]
Are you sure its a problem of the code? I just tried right now and with the parameters i said, it igves different outputs

**Comment by andupotorac** [comment]
Thanks, it works!

**Comment by Nick088Official** [comment]
No problem, you're welcome!
